Repository z88dk/z88dk, pull requests merged in 2021-02, with the labels that each got.

#1694 Issue #1692: (classic) rst handling
  lib/config/laser500.cfg
  lib/crt/classic/crt_rules.inc
  lib/crt/classic/crt_z80_rsts.asm
  lib/crt/classic/tms9918/interrupt.asm
  lib/crt/classic/tms9918/interrupt_handler.asm
  lib/target/altair8800/classic/altair8800_crt0.asm
  lib/target/coleco/classic/coleco_crt0.asm
  lib/target/embedded/classic/embedded_crt0.asm
  lib/target/hemc/classic/hemc_crt0.asm
  lib/target/hgmc/classic/hgmc_crt0.asm
  lib/target/krokha/classic/krokha_crt0.asm
  lib/target/laser500/classic/rom.asm
  lib/target/lviv/classic/lviv_crt0.asm
  lib/target/m5/classic/rom.asm
  lib/target/mikro80/classic/mikro80_crt0.asm
  lib/target/multi8/classic/64k.asm
  lib/target/myvision/classic/myvision_crt0.asm
  lib/target/pasopia7/classic/pasopia7_crt0.asm
  lib/target/pencil2/classic/pencil2_crt0.asm
  lib/target/pmd85/classic/pmd85_crt0.asm
  lib/target/pv1000/classic/pv1000_crt0.asm
  lib/target/sc3000/classic/rom.asm
  lib/target/special/classic/special_crt0.asm
  lib/target/super80/classic/super80_crt0.asm
  lib/target/sv8000/classic/sv8000_crt0.asm
  lib/target/svi/classic/rom.asm
  lib/target/test/classic/test_crt0.asm
  lib/target/x1/classic/allram.asm
  lib/target/x1/classic/ipl.asm
  lib/target/x1/classic/x1_crt0.asm
  lib/target/z80tvgame/classic/z80tvgame_crt0.asm
  src/sccz80/codegen.c
Labels: classiclib, enhancement

#1700 rc2014 - shadow RAM tools
  include/_DEVELOPMENT/clang/arch/rc2014.h
  include/_DEVELOPMENT/proto/arch/rc2014.h
  include/_DEVELOPMENT/sccz80/arch/rc2014.h
  include/_DEVELOPMENT/sdcc/arch/rc2014.h
  libsrc/_DEVELOPMENT/target/rc2014/config/config_target.m4
  libsrc/_DEVELOPMENT/target/rc2014/config_rc2014.h
  libsrc/_DEVELOPMENT/target/rc2014/config_rc2014_private.inc
  libsrc/_DEVELOPMENT/target/rc2014/config_rc2014_public.inc
  libsrc/_DEVELOPMENT/target/rc2014/driver/driver_sccz80.lst
  libsrc/_DEVELOPMENT/target/rc2014/driver/driver_sdcc_ix.lst
  libsrc/_DEVELOPMENT/target/rc2014/driver/driver_sdcc_iy.lst
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sccz80/shadowread.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sccz80/shadowread_callee.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sccz80/shadowwrite.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sccz80/shadowwrite_callee.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sdcc/shadowread.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sdcc/shadowread_callee.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sdcc/shadowwrite.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/c/sdcc/shadowwrite_callee.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/ram_asm.lst
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/ram_sccz80.lst
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/ram_sdcc.lst
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/z80/asm_pop_ei.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/z80/asm_push_di.asm
  libsrc/_DEVELOPMENT/target/rc2014/driver/ram/z80/asm_shadowcopy.asm
  libsrc/_DEVELOPMENT/target/rc2014/startup/rc2014_crt_0.asm.m4
  libsrc/_DEVELOPMENT/target/rc2014/startup/rc2014_crt_4.asm.m4
Labels: enhancement, newlib

#1705 zsdcc - update to 4.1.0 Release
  Makefile
  changelog.txt
  src/zsdcc/readme.md
  src/zsdcc/sdcc-12070-z88dk.patch
  src/zsdcc/sdcc-z88dk.patch
Labels: enhancement, zsdcc
